### ISSUE TITLE
Morty panic

### ISSUE THREAD

**Issue by flaviens** [pulp-platform/morty#47]
Hi there!

On some input, Morty seems to panic with
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/lib.rs:92:83
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

[You can refer to this repository to reproduce the issue and test your fix.](https://github.com/flaviens/mortycrash)

Thanks!
Flavien

**Comment by micprog** [comment]
@flaviens Thanks for finding this bug! Let me know if #48 fixes your issue.

**Comment by flaviens** [comment]
Looks good! That was fast! Thanks!
