### ISSUE TITLE
Parse error on generate begin

### ISSUE THREAD

**Issue by flaviens** [pulp-platform/morty#50]
Hi there!

Morty throws a parse error on this file:

```
module mymodule (
    y,
    a,
    b
);
  parameter WIDTH = 1;
  output [0:WIDTH-1] y;
  input [0:WIDTH-1] a;
  input [0:WIDTH-1] b;

  genvar i;

  generate
    begin : t
      for (i = 0; i < WIDTH; i = i + 1) begin : w

        assign y[i] = a[i] ^ b[i];

      end  // block: w
    end

  endgenerate
endmodule
```

The error message is

```
Error: parse error
   --> main.v:14:10
   |
14 |     begin : t
   |          ^
Error: Parse error: Some(("main.v", 168))
```

Unfortunately [the a2o repository](https://github.com/openpower-cores/a2o) is full of such occurrences.

Thanks!

**Comment by zarubaf** [comment]
I think the `begin` is not legal SystemVerilog. It is `generate`/`endgenerate` (https://www.systemverilog.io/generate). Or http://courses.eees.dei.unibo.it/LABMPHSENG/wp-content/uploads/2016/02/SystemVerilog_3.1a.pdf *A.4.2.1 Generated module instantiation*.

**Comment by flaviens** [comment]
Hi Florian, thank you for your answer!

Given that this pattern is present in the wild and accepted by other tools (I tried Verilator for example), do you think it should be accepted by Morty as well?
